services:
 agent_db:
  image: postgres:15
  environment:
    POSTGRES_USER: hamza
    POSTGRES_PASSWORD: hamza123
    POSTGRES_DB: agentdb
  ports:
    - "5434:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data
  networks:
    - agent-network

volumes:
  pgdata:
networks:
  agent-network: